### ISSUE TITLE
饭否每日精选历史数据补充

### ISSUE THREAD

**Issue by demostars** [movii/Wechat-Fanfou-Daily#1]
您好，同样为饭否爱好者。

经过分析，饭否官方的接口 
http://blog.fanfou.com/digest/json/index.json
最早只保留到 /json/2015-10-05.daily.json 然而经过搜索，在此之前也存在饭否每日精选。

不过没有规律的网址，但是，发现一个不错的信息来源，Google Groups。
https://groups.google.com/forum/#!forum/fanfou-digest

最早可以追溯到2012年3月，至于这是不是最早开始饭否每日精选的日子，我就不得而知了。
http://blog.fanfou.com/2012/03/06/proverbs-328/

使用https://github.com/icy/google-group-crawler 这个项目，完成对Google Groups分析，获得RFC822邮件模式的爬虫。进一步处理后，将RFC822解码转换成HTML形式。

这部分，不知道作者您是否愿意补充到数据库中？如有需要，我可将相关分析后文件上传给您，以免去重复劳动（爬取过程中还是遇到不大不小的问题，还是在原作者的帮助下完成爬取的）

期待您的回复~

**Comment by movii** [comment]
你好，

首先感谢你，这个我自己都不知，看到像是发现了一块新大陆。其次也是相当愿意的。你解析完的 HTML 形式的数据请发我一份（邮箱：[mo.strangeline@gmail.com](mailto:mo.strangeline@gmail.com)），我尝试一下把数据粘合起来。

**Comment by movii** [comment]
邮件已收，记录一下。

大致看了下数据，感觉再进一步过滤、提取应该可用，容我之后尝试一下。
再次感谢 @demostars 抓取、分析提取数据 👍。

**Comment by movii** [comment]
@demostars 你好

虽然晚了很久，但提供的”饭否每日精选“数据已导入完毕，已右键回复，这里 mark 一下完成时间。
再次感谢。
